import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { projectPaths } from "./project.js";
import { ensureDir, moduleSlug, rel, slugify, writeJson, readJson } from "./util.js";
import { scanRepository, normalizePath } from "./scanner.js";
import { planModules } from "./planner.js";
import { resolveGenerationStrategy } from "./llm.js";
import { runDirectGeneration } from "./generator/direct.js";
import { runReactGeneration } from "./generator/react.js";
import { runExternalGeneration } from "./generator/external.js";
import { requiredDesignSections, requiredSpecSections } from "./generator/templates.js";
import { isZh, tr } from "./i18n.js";

const STUB_MARKER = "<!-- generated by matspec stub -->";
const LANGUAGE_BY_EXTENSION = {
  ".js": "JavaScript",
  ".jsx": "JavaScript",
  ".ts": "TypeScript",
  ".tsx": "TypeScript",
  ".py": "Python",
  ".go": "Go",
  ".rs": "Rust",
  ".java": "Java",
  ".kt": "Kotlin",
  ".cs": "C#",
  ".php": "PHP",
  ".rb": "Ruby",
  ".c": "C/C++",
  ".cc": "C/C++",
  ".cpp": "C/C++",
  ".h": "C/C++",
  ".hpp": "C/C++",
  ".swift": "Swift"
};

export async function generateDocs(options = {}) {
  const paths = projectPaths(options);
  progress(options, tr(options, "Checking MatSpec project structure", "检查 matspec 项目结构"));
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const preflightStrategy = resolveGenerationStrategy(paths, options);
  if (!preflightStrategy.ok) return preflightStrategy;

  const run = createRun(paths, "generate", options);
  progress(options, tr(options, `Creating run ${run.manifest.runId}`, `创建 run ${run.manifest.runId}`));
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);
  copyKnowledge(paths.root, run.dir, options.knowledge);

  progress(options, tr(options, "Scanning repository files", "扫描仓库文件"));
  const scan = scanRepository(paths.root);
  progress(options, tr(options, `Scan complete: ${scan.includedFiles.length} files included, ${scan.ignoredFiles.count} entries ignored`, `扫描完成：纳入 ${scan.includedFiles.length} 个文件，忽略 ${scan.ignoredFiles.count} 个条目`));
  progress(options, tr(options, "Planning modules", "规划模块"));
  const plan = planModules(paths.root, scan);
  progress(options, tr(options, `Module plan complete: ${plan.modules.length} modules, primary language ${plan.language || "unknown"}`, `模块规划完成：${plan.modules.length} 个模块，主语言 ${plan.language || "unknown"}`));
  writeJson(path.join(logsDir, "scan.json"), scan);
  writeJson(path.join(logsDir, "key-files.json"), selectKeyFiles(scan));
  writeJson(path.join(run.dir, "plan.json"), plan);

  const strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return failRun(run, strategy);
  progress(options, tr(options, `Generation strategy: runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`));

  const specPath = path.join(run.dir, "spec.md");
  const designPath = path.join(run.dir, "design.md");
  if (strategy.generationMode === "direct") {
    progress(options, tr(options, "Direct mode: generate design.md, then derive spec.md from design.md", "整体 direct：生成 design.md，然后从 design.md 反推 spec.md"));
    const direct =
      strategy.provider === "fake"
        ? runDirectGeneration({ paths, run, scan, plan, strategy, options })
        : runExternalGeneration({ paths, run, scan, plan, strategy, options });
    if (!direct.ok && !direct.design) return failRun(run, direct);
    fs.writeFileSync(designPath, direct.design, "utf8");
    fs.writeFileSync(specPath, direct.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "direct",
      runner: strategy.runner,
      provider: direct.provider,
      model: direct.model,
      tokens: direct.tokens,
      logs: direct.logs,
      warnings:
        strategy.provider === "fake"
          ? ["P2 fake direct output; no real network LLM was called."]
          : ["P2 CLI runner direct output; artifacts were staged under the run directory."],
      reason: strategy.generationReason
    });
  } else if (strategy.generationMode === "react") {
    progress(options, tr(options, `Module-first mode: generate module docs, compose design.md, then derive spec.md (${plan.modules.length} modules, about ${plan.modules.length + 2} runner calls)`, `模块优先生成：逐模块生成文档，合成 design.md，然后反推 spec.md（${plan.modules.length} 个模块，预计 ${plan.modules.length + 2} 次 runner 调用）`));
    const react = await runReactGeneration({ paths, run, scan, plan, strategy, progress: options.progress, options });
    if (!react.ok) return failRun(run, react);
    fs.writeFileSync(designPath, react.design, "utf8");
    fs.writeFileSync(specPath, react.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "react",
      runner: strategy.runner,
      provider: react.provider,
      model: react.model,
      tokens: react.tokens,
      logs: react.logs,
      modules: react.modules,
      moduleFailures: react.moduleFailures,
      status: react.moduleFailures?.length ? "partial_success" : "generated",
      warnings:
        strategy.provider === "fake"
          ? ["P3 fake react output; no real network LLM was called."]
          : [
              "P3 CLI runner react output; module artifacts were staged under the run directory.",
              ...(react.moduleFailures?.length ? [`P2 partial_success; ${react.moduleFailures.length} module(s) failed after fallback attempts.`] : [])
            ],
      reason: react.reason
    });
  } else {
    progress(options, tr(options, "No local runner found; writing deterministic stub artifacts", "未发现可用本地 runner，写入 deterministic stub"));
    fs.writeFileSync(designPath, designStub(paths.root, run.manifest, options), "utf8");
    fs.writeFileSync(specPath, specStub(paths.root, run.manifest, options), "utf8");
    run.manifest.generationReason = strategy.generationReason;
    run.manifest.warnings = [
      ...new Set([
        ...(run.manifest.warnings || []).filter((warning) => !String(warning).startsWith("P0 deterministic stub")),
        tr(options, "No local generation tool found; deterministic stub was used.", "未发现可用的本地生成工具，已使用 deterministic stub。")
      ])
    ];
  }

  run.manifest.artifacts.spec = "spec.md";
  run.manifest.artifacts.design = "design.md";
  run.manifest.plantUml = validatePlantUml(fs.readFileSync(designPath, "utf8"));
  run.manifest.artifacts.plan = "plan.json";
  run.manifest.logs.scan = "logs/scan.json";
  run.manifest.logs.keyFiles = "logs/key-files.json";
  run.manifest.scanSummary = {
    totalFiles: scan.totalFiles,
    includedFiles: scan.includedFiles.length,
    ignoredFiles: scan.ignoredFiles.count,
    readmeFiles: scan.readmeFiles.map((file) => file.path),
    docsFiles: scan.docsFiles.map((file) => file.path)
  };
  run.manifest.planSummary = {
    modules: plan.modules.length,
    language: plan.language,
    primaryExtension: plan.primaryExtension
  };
  if (run.manifest.status === "running") run.manifest.status = "generated";
  writeManifest(paths, run);
  progress(options, tr(options, "Writing manifest and latest pointer", "写入 manifest 和 latest 指针"));

  return {
    ok: true,
    runId: run.manifest.runId,
    status: run.manifest.status,
    artifacts: [rel(paths.root, specPath), rel(paths.root, designPath)],
    message: tr(options, `Generated candidate documents: ${run.manifest.runId}`, `已生成候选文档：${run.manifest.runId}`),
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      files: `${scan.includedFiles.length} included / ${scan.ignoredFiles.count} ignored`,
      modules: plan.modules.length,
      run: rel(paths.root, run.dir)
    },
    sections: [
      {
        title: tr(options, "Artifacts", "产物"),
        items: [rel(paths.root, specPath), rel(paths.root, designPath), rel(paths.root, path.join(run.dir, "plan.json")), rel(paths.root, path.join(logsDir, "scan.json"))]
      },
      {
        title: tr(options, "Review suggestions", "审查建议"),
        items: isZh(options) ? ["先执行 matspec show 查看摘要", "确认内容后执行 matspec apply 写入 matspec/specs"] : ["Run matspec show to review the summary", "After review, run matspec apply to write matspec/specs"]
      }
    ],
    next: ["matspec show", "matspec apply"]
  };
}

export async function generateModule(modulePath, options = {}) {
  const requestedModulePaths = (Array.isArray(modulePath) ? modulePath : [modulePath]).filter(Boolean);
  if (!requestedModulePaths.length) {
    return {
      ok: false,
      code: "MISSING_MODULE_PATH",
      message: tr(options, "Missing module path: matspec generate module <path>", "缺少模块路径：matspec generate module <path>")
    };
  }
  const paths = projectPaths(options);
  progress(options, tr(options, "Checking MatSpec project structure", "检查 matspec 项目结构"));
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;

  const relativeModulePaths = requestedModulePaths.map((item) => normalizeModulePath(paths.root, item));
  const relativeModulePath = relativeModulePaths[0];
  progress(options, tr(options, `Preparing module path: ${relativeModulePaths.join(", ")}`, `准备模块路径：${relativeModulePaths.join("、")}`));
  const scan = scanRepository(paths.root);
  const plans = relativeModulePaths.map((item) => moduleOnlyPlan(paths.root, item, scan));
  const plan = {
    ...plans[0],
    modules: [...new Map(plans.flatMap((item) => item.modules).map((module) => [module.path, module])).values()]
  };
  let strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return strategy;
  if (strategy.generationMode === "direct") {
    strategy = {
      ...strategy,
      generationMode: "react",
      generationReason: "focused_module_forces_module_first"
    };
  }
  progress(options, tr(options, `Generation strategy: runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`));

  const run = createRun(paths, "generate", options);
  run.manifest.scope = "focused_module";
  run.manifest.focusedModule = relativeModulePath;
  if (relativeModulePaths.length > 1) run.manifest.focusedModules = relativeModulePaths;
  const modulesDir = path.join(run.dir, "modules");
  ensureDir(modulesDir);
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);
  copyKnowledge(paths.root, run.dir, options.knowledge);
  writeJson(path.join(logsDir, "scan.json"), scan);
  writeJson(path.join(logsDir, "key-files.json"), selectKeyFiles(scan));
  writeJson(path.join(run.dir, "plan.json"), plan);
  run.manifest.artifacts.plan = "plan.json";
  run.manifest.logs.scan = "logs/scan.json";
  run.manifest.logs.keyFiles = "logs/key-files.json";
  run.manifest.scanSummary = scanSummary(scan);
  run.manifest.planSummary = planSummary(plan);

  for (const item of relativeModulePaths) {
    if (modulePathExists(paths.root, item)) continue;
    const warning = `module path not found: ${item}`;
    if (!run.manifest.warnings.includes(warning)) run.manifest.warnings.push(warning);
  }

  const specPath = path.join(run.dir, "spec.md");
  const designPath = path.join(run.dir, "design.md");
  if (strategy.generationMode === "react") {
    progress(options, tr(options, "Focused module-first mode: generate module doc, compose design.md, then derive spec.md", "聚焦模块优先生成：生成模块文档，合成 design.md，然后反推 spec.md"));
    const react = await runReactGeneration({
      paths,
      run,
      scan,
      plan,
      strategy,
      progress: options.progress,
      options: { ...options, ...(relativeModulePaths.length === 1 ? { focusedModule: relativeModulePath } : {}) }
    });
    if (!react.ok) {
      applyGenerationMetadata(run.manifest, {
        generationMode: "react",
        runner: strategy.runner,
        provider: react.provider || strategy.provider,
        model: react.model || strategy.model,
        tokens: react.tokens,
        logs: react.logs,
        modules: react.modules,
        moduleFailures: react.moduleFailures,
        warnings: nonStubWarnings(
          run.manifest,
          strategy.provider === "fake"
            ? ["P3 fake focused react output; no real network LLM was called."]
            : ["P3 CLI runner focused react output; artifacts were staged under the run directory."]
        ),
        reason: react.reason || strategy.generationReason
      });
      return failRun(run, react);
    }
    fs.writeFileSync(designPath, react.design, "utf8");
    fs.writeFileSync(specPath, react.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "react",
      runner: strategy.runner,
      provider: react.provider,
      model: react.model,
      tokens: react.tokens,
      logs: react.logs,
      modules: react.modules,
      moduleFailures: react.moduleFailures,
      warnings: nonStubWarnings(
        run.manifest,
        strategy.provider === "fake"
          ? ["P3 fake focused react output; no real network LLM was called."]
          : ["P3 CLI runner focused react output; artifacts were staged under the run directory."]
      ),
      reason: react.reason
    });
  } else {
    const fileName = `${moduleSlug(relativeModulePath)}.md`;
    const moduleFile = path.join(modulesDir, fileName);
    fs.writeFileSync(moduleFile, moduleStub(relativeModulePath, run.manifest, options), "utf8");
    fs.writeFileSync(designPath, focusedDesignStub(paths.root, relativeModulePath, run.manifest, options), "utf8");
    fs.writeFileSync(specPath, focusedSpecStub(paths.root, relativeModulePath, run.manifest, options), "utf8");
    run.manifest.generationReason = strategy.generationReason;
    run.manifest.artifacts.modules = [`modules/${fileName}`];
    run.manifest.warnings = [
      ...new Set([
        ...(run.manifest.warnings || []).filter((warning) => !String(warning).startsWith("P0 deterministic stub")),
        tr(options, "No local generation tool found; deterministic stub was used.", "未发现可用的本地生成工具，已使用 deterministic stub。")
      ])
    ];
  }

  run.manifest.artifacts.spec = "spec.md";
  run.manifest.artifacts.design = "design.md";
  run.manifest.plantUml = validatePlantUml(fs.readFileSync(designPath, "utf8"));
  run.manifest.updatedAt = new Date().toISOString();
  if (run.manifest.status === "running") run.manifest.status = "generated";
  writeManifest(paths, run);

  return {
    ok: true,
    runId: run.manifest.runId,
    module: relativeModulePath,
    modules: relativeModulePaths,
    artifact: run.manifest.artifacts.modules[0] ? rel(paths.root, path.join(run.dir, run.manifest.artifacts.modules[0])) : null,
    artifacts: [rel(paths.root, specPath), rel(paths.root, designPath), ...run.manifest.artifacts.modules.map((artifact) => rel(paths.root, path.join(run.dir, artifact)))],
    message: tr(options, `Generated focused candidate documents: ${relativeModulePath}`, `已生成聚焦模块候选文档：${relativeModulePath}`),
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      run: rel(paths.root, run.dir)
    },
    sections: [{ title: tr(options, "Artifacts", "产物"), items: [rel(paths.root, specPath), rel(paths.root, designPath), ...run.manifest.artifacts.modules.map((artifact) => rel(paths.root, path.join(run.dir, artifact)))] }],
    next: ["matspec show", "matspec apply"]
  };
}

export function showLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: tr(options, "No candidate documents found. Run matspec generate first.", "未发现候选文档。请先执行 matspec generate。")
    };
  }
  if (options.json) return latest.manifest;

  const manifest = latest.manifest;
  const modules = manifest.artifacts.modules || [];
  const plan = readRunJson(latest, manifest.artifacts.plan);
  const scan = readRunJson(latest, manifest.logs?.scan);
  const plannedModules = plan?.modules?.length ?? manifest.planSummary?.modules ?? 0;
  const includedFiles = scan?.includedFiles?.length ?? manifest.scanSummary?.includedFiles ?? null;
  const hasFullArtifacts = Boolean(manifest.artifacts.spec && manifest.artifacts.design);
  return {
    ok: true,
    runId: manifest.runId,
    message: tr(options, `Candidate documents: ${manifest.runId}`, `候选文档：${manifest.runId}`),
    items: [
      tr(options, `Status: ${manifest.status}`, `状态：${manifest.status}`),
      `Commit：${manifest.commitId || "unknown"}`,
      "",
      tr(options, "Artifacts:", "产物："),
      manifest.artifacts.spec ? `  ${manifest.artifacts.spec}` : tr(options, "  spec.md not generated", "  spec.md 未生成"),
      manifest.artifacts.design ? `  ${manifest.artifacts.design}` : tr(options, "  design.md not generated", "  design.md 未生成"),
      `  modules/ ${modules.length} files`,
      manifest.artifacts.plan ? `  ${manifest.artifacts.plan}` : tr(options, "  plan.json not generated", "  plan.json 未生成"),
      manifest.logs?.scan ? `  ${manifest.logs.scan}` : tr(options, "  logs/scan.json not generated", "  logs/scan.json 未生成"),
      "",
      tr(options, "Summary:", "摘要："),
      `  generation mode: ${displayGenerationMode(manifest.generationMode)}`,
      `  runner: ${manifest.runner || "auto"}`,
      `  provider: ${manifest.provider || "none"}`,
      `  model: ${manifest.model || "none"}`,
      `  included files: ${includedFiles ?? "unknown"}`,
      `  planned modules: ${plannedModules}`,
      "",
      tr(options, "Location:", "文件位置："),
      `  ${rel(paths.root, latest.dir)}/`,
      ...(hasFullArtifacts ? [] : ["", tr(options, "Hint: this is a module-only run. Run matspec generate before apply.", "提示：这是 module-only run，请先执行 matspec generate 后再 apply。")])
    ],
    next: hasFullArtifacts ? ["matspec apply"] : ["matspec generate"]
  };
}

export function applyLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: tr(options, "No candidate documents found. Run matspec generate first.", "未发现候选文档。请先执行 matspec generate。")
    };
  }
  if (latest.manifest.status === "partial_success" && !options.force) {
    return {
      ok: false,
      code: "APPLY_PARTIAL_SUCCESS_REQUIRES_FORCE",
      message: tr(options, "The latest candidate run is partial_success. Use matspec apply --force if you still want to apply it.", "最近一次候选文档为 partial_success。如确认仍要应用，请执行 matspec apply --force。")
    };
  }

  const specSource = path.join(latest.dir, "spec.md");
  const designSource = path.join(latest.dir, "design.md");
  const missing = [specSource, designSource].filter((file) => !fs.existsSync(file));
  if (missing.length) {
    return {
      ok: false,
      code: "RUN_ARTIFACT_MISSING",
      message: tr(options, `Candidate documents are incomplete: ${missing.map((file) => rel(paths.root, file)).join(", ")}`, `候选文档不完整：${missing.map((file) => rel(paths.root, file)).join(", ")}`)
    };
  }

  const quality = validateApplyArtifacts(specSource, designSource, options);
  if (!quality.ok) return quality;

  const specTarget = path.join(paths.specs, "spec.md");
  const designTarget = path.join(paths.specs, "design.md");
  const existing = [specTarget, designTarget].filter((file) => fs.existsSync(file));
  if (existing.length && !options.force) {
    return {
      ok: false,
      code: "APPLY_OVERWRITE_REQUIRED",
      message: tr(options, "matspec/specs/spec.md or matspec/specs/design.md already exists. Use matspec apply --force to overwrite.", "已存在 matspec/specs/spec.md 或 matspec/specs/design.md。如需覆盖，请执行 matspec apply --force。"),
      existing: existing.map((file) => rel(paths.root, file))
    };
  }

  fs.mkdirSync(paths.specs, { recursive: true });
  fs.copyFileSync(specSource, specTarget);
  fs.copyFileSync(designSource, designTarget);

  latest.manifest.applied = true;
  latest.manifest.appliedAt = new Date().toISOString();
  writeManifest(paths, latest);

  return {
    ok: true,
    runId: latest.manifest.runId,
    applied: [rel(paths.root, specTarget), rel(paths.root, designTarget)],
    message: tr(options, `Applied candidate documents: ${latest.manifest.runId}`, `已应用候选文档：${latest.manifest.runId}`),
    items: [rel(paths.root, specTarget), rel(paths.root, designTarget)]
  };
}

function validateApplyArtifacts(specFile, designFile, options = {}) {
  const spec = fs.readFileSync(specFile, "utf8");
  const design = fs.readFileSync(designFile, "utf8");
  const findings = [];
  if (!spec.trim()) findings.push({ level: "error", code: "SPEC_EMPTY", path: "spec.md", message: tr(options, "spec.md is empty.", "spec.md 为空。") });
  if (!design.trim()) findings.push({ level: "error", code: "DESIGN_EMPTY", path: "design.md", message: tr(options, "design.md is empty.", "design.md 为空。") });

  for (const section of requiredSpecSections(options)) {
    if (!containsAnySection(spec, section)) {
      findings.push({ level: "error", code: "SPEC_SECTION_MISSING", path: "spec.md", message: tr(options, `spec.md is missing required section: ${displaySection(section)}`, `spec.md 缺少固定章节：${displaySection(section)}`) });
    }
  }
  for (const section of requiredDesignSections(options)) {
    if (!containsAnySection(design, section)) {
      findings.push({ level: "error", code: "DESIGN_SECTION_MISSING", path: "design.md", message: tr(options, `design.md is missing required section: ${displaySection(section)}`, `design.md 缺少固定章节：${displaySection(section)}`) });
    }
  }
  for (const finding of forbiddenGeneratedOutput(spec, "spec.md", options)) findings.push(finding);
  for (const finding of forbiddenGeneratedOutput(design, "design.md", options)) findings.push(finding);

  if (!findings.length) return { ok: true };
  return {
    ok: false,
    code: "APPLY_QUALITY_FAILED",
    message: tr(options, "Candidate documents failed pre-apply quality checks.", "候选文档未通过 apply 前质量检查。"),
    findings,
    next: isZh(options) ? ["matspec show", "查看 .matspec-cli/runs/{run-id}/spec.md 和 design.md"] : ["matspec show", "Inspect .matspec-cli/runs/{run-id}/spec.md and design.md"]
  };
}

function containsAnySection(text, section) {
  const sections = Array.isArray(section) ? section : [section];
  return sections.some((item) => containsSection(text, item));
}

function containsSection(text, section) {
  return text.replace(/\s+/g, "").toLowerCase().includes(String(section).replace(/\s+/g, "").toLowerCase());
}

function displaySection(section) {
  return Array.isArray(section) ? section[0] : section;
}

function forbiddenGeneratedOutput(text, file, options = {}) {
  const findings = [];
  const trimmed = text.trim();
  if (/^```(?:md|markdown)?\s*#/i.test(trimmed) && /```\s*$/i.test(trimmed)) {
    findings.push({ level: "error", code: "WHOLE_DOCUMENT_CODE_FENCE", path: file, message: tr(options, `${file} is wrapped entirely in a Markdown code fence.`, `${file} 被整体包裹在 Markdown 代码围栏中。`) });
  }
  const forbidden = [
    { pattern: /\b(?:this|the)\s+sandbox\b|\bsandbox\s+environment\b|\bread-?only\s+sandbox\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "sandbox environment" },
    { pattern: /\bread-?only\s+filesystem\b|\bfilesystem\s+access\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "filesystem access" },
    { pattern: /\bread-?only\s+(?:mode|environment|access)\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "read-only environment" },
    { pattern: /cannot write files|could not write files|can't write files/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "cannot write files" },
    { pattern: /copy (?:this|the following|into|to your repo)/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "copy into repo" },
    { pattern: /^(?:sure|certainly|of course|好的|当然|可以)[,，!！:\s]/i, code: "RUNNER_CONVERSATION_TEXT", label: "conversational preface" },
    { pattern: /(?:would you like|please confirm|请确认|是否继续)/i, code: "RUNNER_CONVERSATION_TEXT", label: "confirmation request" },
    { pattern: /(?:continued in the next|to be continued|内容已截断|下文继续)/i, code: "RUNNER_TRUNCATED_OUTPUT", label: "truncation statement" }
  ];
  for (const item of forbidden) {
    if (item.pattern.test(text)) {
      findings.push({ level: "error", code: item.code, path: file, message: tr(options, `${file} contains runner environment text: ${item.label}`, `${file} 包含 runner 环境说明：${item.label}`) });
    }
  }
  return findings;
}

function copyKnowledge(root, runDir, inputs) {
  const values = Array.isArray(inputs) ? inputs : inputs ? [inputs] : [];
  for (const input of values) {
    const source = path.resolve(root, input);
    if (!fs.existsSync(source)) throw Object.assign(new Error(`Knowledge path not found: ${input}`), { code: "KNOWLEDGE_NOT_FOUND", path: input });
    const target = path.join(runDir, "knowledge", path.basename(source));
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.cpSync(source, target, { recursive: true, force: true });
  }
}

function selectKeyFiles(scan) {
  return (scan.sourceFileStats || [])
    .filter((file) => !file.isTestOrExample)
    .sort((left, right) => (right.nonEmptyLines || right.lines || 0) - (left.nonEmptyLines || left.lines || 0))
    .slice(0, 30)
    .map((file) => ({ path: file.path, lines: file.lines, nonEmptyLines: file.nonEmptyLines, language: file.language }));
}

function validatePlantUml(markdown) {
  const blocks = [...markdown.matchAll(/```plantuml\s*([\s\S]*?)```/gi)].map((match) => match[1]);
  const errors = [];
  blocks.forEach((block, index) => {
    if (!/@startuml\b/i.test(block) || !/@enduml\b/i.test(block)) errors.push({ block: index + 1, message: "PlantUML block must contain @startuml and @enduml." });
  });
  return { blocks: blocks.length, valid: errors.length === 0, remainingErrors: errors };
}

function progress(options, message) {
  if (typeof options.progress === "function") options.progress(message);
}

function displayGenerationMode(mode) {
  if (mode === "react") return "module-first";
  if (mode === "direct") return "whole-project-direct";
  return mode || "unknown";
}

function createRun(paths, type, options = {}) {
  const runId = uniqueRunId(paths);
  const dir = path.join(paths.runtime, "runs", runId);
  fs.mkdirSync(dir, { recursive: true });
  const manifest = {
    runId,
    type,
    status: "running",
    createdAt: new Date().toISOString(),
    root: paths.root,
    commitId: currentCommit(paths.root),
    runner: options.runner || "auto",
    generationMode: "stub",
    provider: null,
    model: options.model || null,
    probeModels: {
      requested: Boolean(options.probe_models),
      status: options.probe_models ? "not_implemented" : "not_requested"
    },
    artifacts: {
      spec: null,
      design: null,
      plan: null,
      modules: []
    },
    logs: {
      scan: null,
      llm: null,
      prompts: {}
    },
    warnings: ["P0 deterministic stub output; no LLM was called."],
    tokens: {
      input: 0,
      output: 0
    },
    applied: false
  };
  return { dir, manifest, paths };
}

function applyGenerationMetadata(manifest, metadata) {
  manifest.runner = metadata.runner || manifest.runner;
  manifest.generationMode = metadata.generationMode;
  manifest.provider = metadata.provider || null;
  manifest.model = metadata.model || null;
  manifest.tokens = metadata.tokens || manifest.tokens;
  manifest.generationReason = metadata.reason || null;
  manifest.warnings = metadata.warnings || manifest.warnings;
  if (metadata.status) manifest.status = metadata.status;
  if (metadata.moduleFailures) manifest.moduleFailures = metadata.moduleFailures;
  if (metadata.logs?.llm) manifest.logs.llm = metadata.logs.llm;
  if (metadata.logs?.react) manifest.logs.react = metadata.logs.react;
  if (metadata.logs?.external) manifest.logs.external = metadata.logs.external;
  if (metadata.logs?.prompts) manifest.logs.prompts = metadata.logs.prompts;
  if (metadata.modules) manifest.artifacts.modules = metadata.modules;
}

function failRun(run, error) {
  run.manifest.status = "failed";
  run.manifest.error = {
    code: error.code,
    message: error.message
  };
  writeManifest(run.paths, run);
  return { ...error, runId: run.manifest.runId };
}

function writeManifest(paths, run) {
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  writeJson(path.join(paths.runtime, "runs", "latest.json"), {
    runId: run.manifest.runId,
    manifest: rel(paths.root, path.join(run.dir, "manifest.json"))
  });
}

function loadLatestRun(paths) {
  const latestFile = path.join(paths.runtime, "runs", "latest.json");
  const latest = readJson(latestFile);
  if (latest?.runId) {
    const dir = path.join(paths.runtime, "runs", latest.runId);
    const manifest = readJson(path.join(dir, "manifest.json"));
    if (manifest) return { dir, manifest };
  }

  const runsDir = path.join(paths.runtime, "runs");
  if (!fs.existsSync(runsDir)) return null;
  const manifests = fs
    .readdirSync(runsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dir = path.join(runsDir, entry.name);
      return { dir, manifest: readJson(path.join(dir, "manifest.json")) };
    })
    .filter((run) => run.manifest?.createdAt && run.manifest.status !== "failed")
    .sort((a, b) => String(b.manifest.createdAt).localeCompare(String(a.manifest.createdAt)));
  return manifests[0] || null;
}

function projectInitializationError(paths) {
  if (!fs.existsSync(paths.runtime) || !fs.existsSync(paths.matspec)) {
    return {
      ok: false,
      code: "MATSPEC_NOT_INITIALIZED",
      message: "Missing MatSpec project structure. Run matspec init first.",
      next: ["matspec init"]
    };
  }
  return null;
}

function uniqueRunId(paths) {
  const base = timestampId();
  let runId = base;
  let suffix = 1;
  while (fs.existsSync(path.join(paths.runtime, "runs", runId))) {
    suffix += 1;
    runId = `${base}-${suffix}`;
  }
  return runId;
}

function timestampId(date = new Date()) {
  const pad = (value, size = 2) => String(value).padStart(size, "0");
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds()),
    pad(date.getMilliseconds(), 3)
  ].join("");
}

function currentCommit(root) {
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    timeout: 2000
  });
  return result.status === 0 ? result.stdout.trim() : null;
}

function normalizeModulePath(root, modulePath) {
  const resolved = path.isAbsolute(modulePath) ? modulePath : path.join(root, modulePath);
  const relative = normalizePath(path.relative(root, resolved));
  return relative && !relative.startsWith("..") ? relative : normalizePath(modulePath);
}

function modulePathExists(root, modulePath) {
  if (modulePath === ".") return true;
  return fs.existsSync(path.join(root, modulePath));
}

function readRunJson(run, relativePath) {
  if (!relativePath) return null;
  return readJson(path.join(run.dir, relativePath), null);
}

function scanSummary(scan) {
  return {
    totalFiles: scan.totalFiles,
    includedFiles: scan.includedFiles.length,
    ignoredFiles: scan.ignoredFiles.count,
    readmeFiles: scan.readmeFiles.map((file) => file.path),
    docsFiles: scan.docsFiles.map((file) => file.path)
  };
}

function planSummary(plan) {
  return {
    modules: plan.modules.length,
    language: plan.language,
    primaryExtension: plan.primaryExtension
  };
}

function nonStubWarnings(manifest, warnings) {
  const preserved = (manifest.warnings || []).filter((warning) => !String(warning).startsWith("P0 deterministic stub"));
  return [...new Set([...preserved, ...warnings])];
}

function moduleOnlyPlan(root, modulePath, scan) {
  const primaryExtension = scan.primaryExtension || null;
  return {
    projectName: path.basename(root),
    language: LANGUAGE_BY_EXTENSION[primaryExtension] || null,
    primaryExtension,
    modules: [
      {
        name: moduleName(modulePath),
        path: modulePath,
        description: modulePath === "." ? "Project root module requested by user." : `Module requested by user at ${modulePath}.`
      }
    ]
  };
}

function moduleName(modulePath) {
  if (modulePath === ".") return "Project Root";
  const base = modulePath.split("/").filter(Boolean).pop() || "Module";
  return base
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function designStub(root, manifest, options = {}) {
  if (isZh(options)) {
    return `${STUB_MARKER}
# MatSpec 实现设计

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 设计概述

这个 deterministic stub 用于验证 MatSpec 候选文档生成流程。

## 2. 系统架构

stub 不调用 LLM 或外部 agent。CLI 负责创建 run 目录、写入产物并维护 manifest。

## 3. 数据模型

manifest.json 记录 run ID、状态、产物、runner、模型元数据和 apply 状态。

## 4. 接口设计

用户入口包括 matspec generate、matspec show、matspec apply 和 matspec generate module <path>。

## 5. 核心流程设计

generate 写入候选文档，show 展示最近一次 run，apply 将审查后的产物发布到 matspec/specs 并提供覆盖保护。

## 6. 算法设计

stub 模式不使用复杂算法。

## 7. 缓存设计

stub 模式不使用缓存。

## 8. 异常处理设计

除非显式传入 --force，否则不会覆盖已有权威文档。

## 9. 监控与日志

run 目录保存 manifest 和生成日志。

## 10. 安全设计

stub 内容只是 fallback 产物，不代表真实项目设计结论。
`;
  }
  return `${STUB_MARKER}
# MatSpec Implementation Design

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. Design Overview

This deterministic stub validates the MatSpec candidate document generation pipeline.

## 2. System Architecture

The stub does not call an LLM or external agent. The CLI creates the run directory, writes artifacts, and maintains the manifest.

## 3. Data Model

manifest.json records the run ID, status, artifacts, runner, model metadata, and apply state.

## 4. Interface Design

User-facing entry points are matspec generate, matspec show, matspec apply, and matspec generate module <path>.

## 5. Core Flow Design

generate writes candidate documents, show displays the latest run, and apply publishes reviewed artifacts to matspec/specs with overwrite protection.

## 6. Algorithm Design

Stub mode does not use complex algorithms.

## 7. Caching Design

Stub mode does not use caching.

## 8. Error Handling Design

Existing authoritative documents are not overwritten unless --force is provided.

## 9. Observability

The run directory stores the manifest and generation logs.

## 10. Security Design

Stub content is only a fallback artifact and does not represent a real project design conclusion.
`;
}

function specStub(root, manifest, options = {}) {
  if (isZh(options)) {
    return `${STUB_MARKER}
# MatSpec 规格说明

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. 组件定位

该组件使用 MatSpec CLI 管理候选文档，并发布审查后的权威文档。

## 2. 领域术语

- 候选文档：apply 前存放在 run 目录中的生成文档。
- 权威文档：matspec/specs 下的 spec.md 或 design.md。
- Run：一次生成动作创建的隔离结果目录。

## 3. 角色与边界

CLI 负责产物写入、审查展示和 apply。外部 agent 不能直接写入权威文档。

## 4. DFX 约束

应用候选文档时必须遵守覆盖保护；默认保留已有权威文档。

## 5. 核心能力

- 用户可以生成候选 spec.md 和 design.md。
- 用户可以审查最近一次候选文档摘要。
- 用户可以显式 apply 最近一次候选文档。
- 用户可以为单个模块生成审查材料。

## 6. 数据约束

- generate 只写入 .matspec-cli/runs。
- show 可以返回最近一次 run manifest。
- 目标已存在且未传入 --force 时，apply 必须失败。
`;
  }
  return `${STUB_MARKER}
# MatSpec SPEC

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. Component Purpose

This component uses the MatSpec CLI to manage candidate documents and publish reviewed authoritative documents.

## 2. Domain Terminology

- Candidate document: a generated document stored in a run directory before apply.
- Authoritative document: spec.md or design.md under matspec/specs.
- Run: an isolated result directory created by one generation action.

## 3. Actors and Boundaries

The CLI owns artifact writing, review display, and apply. External agents do not write authoritative documents directly.

## 4. DFX Constraints

Applying candidate documents must respect overwrite protection; existing authoritative documents are preserved by default.

## 5. Core Capabilities

- Users can generate candidate spec.md and design.md.
- Users can review the latest candidate document summary.
- Users can explicitly apply the latest candidate documents.
- Users can generate review material for a single module.

## 6. Data Constraints

- generate writes only to .matspec-cli/runs.
- show can return the latest run manifest.
- apply fails without --force when the target already exists.
`;
}

function focusedDesignStub(root, modulePath, manifest, options = {}) {
  if (isZh(options)) {
    return `${STUB_MARKER}
# MatSpec 聚焦模块实现设计

Run: ${manifest.runId}
Repository: ${path.basename(root)}
Focused module: ${modulePath}

## 1. 设计概述

这是 ${modulePath} 的 deterministic stub 聚焦模块设计，用于验证 focused module 候选文档生成流程。

## 2. 系统架构

stub 不调用 LLM 或外部 agent。CLI 负责为 ${modulePath} 创建 focused run、写入模块文档、design.md、spec.md 并维护 manifest。

## 3. 数据模型

manifest.json 记录 focusedModule、run ID、状态、产物、runner、模型元数据和 apply 状态。

## 4. 接口设计

用户入口为 matspec generate module ${modulePath}。

## 5. 核心流程设计

focused generation 先锁定 ${modulePath}，再生成模块材料、design.md 和 spec.md。

## 6. 算法设计

stub 模式不使用复杂算法。

## 7. 缓存设计

stub 模式不使用缓存。

## 8. 异常处理设计

除非显式传入 --force，否则 apply 不会覆盖已有权威文档。

## 9. 监控与日志

run 目录保存 ${modulePath} 的 manifest、plan、scan 和模块生成日志。

## 10. 安全设计

stub 内容只是 fallback 产物，不代表 ${modulePath} 的真实项目设计结论。
`;
  }
  return `${STUB_MARKER}
# MatSpec Focused Module Implementation Design

Run: ${manifest.runId}
Repository: ${path.basename(root)}
Focused module: ${modulePath}

## 1. Design Overview

This deterministic stub validates focused candidate generation for ${modulePath}.

## 2. System Architecture

The stub does not call an LLM or external agent. The CLI creates a focused run for ${modulePath}, writes the module document, design.md, spec.md, and maintains the manifest.

## 3. Data Model

manifest.json records focusedModule, run ID, status, artifacts, runner, model metadata, and apply state.

## 4. Interface Design

The user-facing entry point is matspec generate module ${modulePath}.

## 5. Core Flow Design

Focused generation locks onto ${modulePath}, then produces module material, design.md, and spec.md.

## 6. Algorithm Design

Stub mode does not use complex algorithms.

## 7. Caching Design

Stub mode does not use caching.

## 8. Error Handling Design

apply does not overwrite existing authoritative documents unless --force is provided.

## 9. Observability

The run directory stores manifest, plan, scan, and module generation logs for ${modulePath}.

## 10. Security Design

Stub content is only a fallback artifact and does not represent the real design of ${modulePath}.
`;
}

function focusedSpecStub(root, modulePath, manifest, options = {}) {
  if (isZh(options)) {
    return `${STUB_MARKER}
# MatSpec 聚焦模块规格说明

Run: ${manifest.runId}
Repository: ${path.basename(root)}
Focused module: ${modulePath}

## 1. 组件定位

${modulePath} 使用 focused module generation 生成候选规格和设计文档。

## 2. 领域术语

- 聚焦模块：用户通过 matspec generate module 指定的源码目录。
- 候选文档：apply 前存放在 run 目录中的 spec.md、design.md 和模块材料。

## 3. 角色与边界

CLI 负责锁定 ${modulePath}、写入候选产物和 apply 保护。外部 agent 不直接写入权威文档。

## 4. DFX 约束

候选文档必须保留 focusedModule 元数据，并在 apply 前接受审查。

## 5. 核心能力

- 用户可以为 ${modulePath} 生成 focused design.md。
- 用户可以为 ${modulePath} 生成 design-derived spec.md。
- 用户可以审查并 apply 最近一次完整 focused run。

## 6. 数据约束

- focused run 必须记录 plan.json、logs/scan.json 和模块产物路径。
- apply 必须要求 spec.md 和 design.md 同时存在。
`;
  }
  return `${STUB_MARKER}
# MatSpec Focused Module SPEC

Run: ${manifest.runId}
Repository: ${path.basename(root)}
Focused module: ${modulePath}

## 1. Component Purpose

${modulePath} uses focused module generation to produce candidate specification and design documents.

## 2. Domain Terminology

- Focused module: the source directory selected through matspec generate module.
- Candidate document: spec.md, design.md, and module material stored in a run directory before apply.

## 3. Actors and Boundaries

The CLI locks onto ${modulePath}, writes candidate artifacts, and enforces apply protection. External agents do not write authoritative documents directly.

## 4. DFX Constraints

Candidate documents must preserve focusedModule metadata and be reviewed before apply.

## 5. Core Capabilities

- Users can generate focused design.md for ${modulePath}.
- Users can generate a design-derived spec.md for ${modulePath}.
- Users can review and apply the latest complete focused run.

## 6. Data Constraints

- Focused runs must record plan.json, logs/scan.json, and module artifact paths.
- apply requires both spec.md and design.md to exist.
`;
}

function moduleStub(modulePath, manifest, options = {}) {
  if (isZh(options)) {
    return `${STUB_MARKER}
# 模块设计：${modulePath}

Run: ${manifest.runId}

## 1. 模块定位

这是 ${modulePath} 的 deterministic stub 模块文档。

## 2. 目录结构

stub 不分析完整文件树；真实生成应补充仓库扫描和模块规划信息。

## 3. 核心组件

待真实代码分析补充。

## 4. 核心流程

该文件只存放在 run/modules 下，不会 apply 到 matspec/specs。

## 5. 接口与数据结构

待确认。

## 6. 关键约束

deterministic stub 不调用 LLM 或外部 runner。
`;
  }
  return `${STUB_MARKER}
# Module Design: ${modulePath}

Run: ${manifest.runId}

## 1. Module Purpose

This is a deterministic stub module document for ${modulePath}.

## 2. Directory Structure

The stub does not analyze the full file tree; real generation should add repository scan and module planning details.

## 3. Core Components

To be filled by real code analysis.

## 4. Core Flows

This file is stored only under run/modules and is not applied to matspec/specs.

## 5. Interfaces and Data Structures

To be confirmed.

## 6. Key Constraints

The deterministic stub does not call an LLM or external runner.
`;
}
