import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { projectPaths } from "./project.js";
import { ensureDir, rel, slugify, writeJson, readJson } from "./util.js";
import { scanRepository, normalizePath } from "./scanner.js";
import { planModules } from "./planner.js";
import { fakeCompletion, resolveGenerationStrategy } from "./llm.js";
import { runDirectGeneration } from "./generator/direct.js";
import { runReactGeneration } from "./generator/react.js";
import { createWorkspaceGuard, runExternalGeneration, runRunnerTask } from "./generator/external.js";
import { commonOutputRules, requiredDesignSections, requiredSpecSections } from "./generator/templates.js";
import { isZh, tr } from "./i18n.js";

const STUB_MARKER = "<!-- generated by matspec stub -->";

export function generateDocs(options = {}) {
  const paths = projectPaths(options);
  progress(options, tr(options, "Checking MatSpec project structure", "检查 matspec 项目结构"));
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const preflightStrategy = resolveGenerationStrategy(paths, options);
  if (!preflightStrategy.ok) return preflightStrategy;

  const run = createRun(paths, "generate", options);
  progress(options, tr(options, `Creating run ${run.manifest.runId}`, `创建 run ${run.manifest.runId}`));
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);

  progress(options, tr(options, "Scanning repository files", "扫描仓库文件"));
  const scan = scanRepository(paths.root);
  progress(options, tr(options, `Scan complete: ${scan.includedFiles.length} files included, ${scan.ignoredFiles.count} entries ignored`, `扫描完成：纳入 ${scan.includedFiles.length} 个文件，忽略 ${scan.ignoredFiles.count} 个条目`));
  progress(options, tr(options, "Planning modules", "规划模块"));
  const plan = planModules(paths.root, scan);
  progress(options, tr(options, `Module plan complete: ${plan.modules.length} modules, primary language ${plan.language || "unknown"}`, `模块规划完成：${plan.modules.length} 个模块，主语言 ${plan.language || "unknown"}`));
  writeJson(path.join(logsDir, "scan.json"), scan);
  writeJson(path.join(run.dir, "plan.json"), plan);

  const strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return failRun(run, strategy);
  progress(options, tr(options, `Generation strategy: runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`));

  const specPath = path.join(run.dir, "spec.md");
  const designPath = path.join(run.dir, "design.md");
  if (strategy.generationMode === "direct") {
    progress(options, tr(options, "Direct mode: generate design.md, then derive spec.md from design.md", "整体 direct：生成 design.md，然后从 design.md 反推 spec.md"));
    const direct =
      strategy.provider === "fake"
        ? runDirectGeneration({ paths, run, scan, plan, strategy })
        : runExternalGeneration({ paths, run, scan, plan, strategy });
    if (!direct.ok && !direct.design) return failRun(run, direct);
    fs.writeFileSync(designPath, direct.design, "utf8");
    fs.writeFileSync(specPath, direct.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "direct",
      runner: strategy.runner,
      provider: direct.provider,
      model: direct.model,
      tokens: direct.tokens,
      logs: direct.logs,
      warnings:
        strategy.provider === "fake"
          ? ["P2 fake direct output; no real network LLM was called."]
          : ["P2 CLI runner direct output; artifacts were staged under the run directory."],
      reason: strategy.generationReason
    });
  } else if (strategy.generationMode === "react") {
    progress(options, tr(options, `Module-first mode: generate module docs, compose design.md, then derive spec.md (${plan.modules.length} modules, about ${plan.modules.length + 2} runner calls)`, `模块优先生成：逐模块生成文档，合成 design.md，然后反推 spec.md（${plan.modules.length} 个模块，预计 ${plan.modules.length + 2} 次 runner 调用）`));
    const react = runReactGeneration({ paths, run, scan, plan, strategy, progress: options.progress });
    if (!react.ok) return failRun(run, react);
    fs.writeFileSync(designPath, react.design, "utf8");
    fs.writeFileSync(specPath, react.spec, "utf8");
    applyGenerationMetadata(run.manifest, {
      generationMode: "react",
      runner: strategy.runner,
      provider: react.provider,
      model: react.model,
      tokens: react.tokens,
      logs: react.logs,
      modules: react.modules,
      warnings:
        strategy.provider === "fake"
          ? ["P3 fake react output; no real network LLM was called."]
          : ["P3 CLI runner react output; module artifacts were staged under the run directory."],
      reason: react.reason
    });
  } else {
    progress(options, tr(options, "No local runner found; writing deterministic stub artifacts", "未发现可用本地 runner，写入 deterministic stub"));
    fs.writeFileSync(designPath, designStub(paths.root, run.manifest), "utf8");
    fs.writeFileSync(specPath, specStub(paths.root, run.manifest), "utf8");
    run.manifest.generationReason = strategy.generationReason;
    run.manifest.warnings = [tr(options, "No local generation tool found; deterministic stub was used.", "未发现可用的本地生成工具，已使用 deterministic stub。")];
  }

  run.manifest.artifacts.spec = "spec.md";
  run.manifest.artifacts.design = "design.md";
  run.manifest.artifacts.plan = "plan.json";
  run.manifest.logs.scan = "logs/scan.json";
  run.manifest.scanSummary = {
    totalFiles: scan.totalFiles,
    includedFiles: scan.includedFiles.length,
    ignoredFiles: scan.ignoredFiles.count,
    readmeFiles: scan.readmeFiles.map((file) => file.path),
    docsFiles: scan.docsFiles.map((file) => file.path)
  };
  run.manifest.planSummary = {
    modules: plan.modules.length,
    language: plan.language,
    primaryExtension: plan.primaryExtension
  };
  writeManifest(paths, run);
  progress(options, tr(options, "Writing manifest and latest pointer", "写入 manifest 和 latest 指针"));

  return {
    ok: true,
    runId: run.manifest.runId,
    status: run.manifest.status,
    artifacts: [rel(paths.root, specPath), rel(paths.root, designPath)],
    message: tr(options, `Generated candidate documents: ${run.manifest.runId}`, `已生成候选文档：${run.manifest.runId}`),
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      files: `${scan.includedFiles.length} included / ${scan.ignoredFiles.count} ignored`,
      modules: plan.modules.length,
      run: rel(paths.root, run.dir)
    },
    sections: [
      {
        title: tr(options, "Artifacts", "产物"),
        items: [rel(paths.root, specPath), rel(paths.root, designPath), rel(paths.root, path.join(run.dir, "plan.json")), rel(paths.root, path.join(logsDir, "scan.json"))]
      },
      {
        title: tr(options, "Review suggestions", "审查建议"),
        items: isZh(options) ? ["先执行 matspec show 查看摘要", "确认内容后执行 matspec apply 写入 matspec/specs"] : ["Run matspec show to review the summary", "After review, run matspec apply to write matspec/specs"]
      }
    ],
    next: ["matspec show", "matspec apply"]
  };
}

export function generateModule(modulePath, options = {}) {
  if (!modulePath) {
    return {
      ok: false,
      code: "MISSING_MODULE_PATH",
      message: tr(options, "Missing module path: matspec generate module <path>", "缺少模块路径：matspec generate module <path>")
    };
  }
  const paths = projectPaths(options);
  progress(options, tr(options, "Checking MatSpec project structure", "检查 matspec 项目结构"));
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;

  const relativeModulePath = normalizeModulePath(paths.root, modulePath);
  progress(options, tr(options, `Preparing module path: ${relativeModulePath}`, `准备模块路径：${relativeModulePath}`));
  const scan = scanRepository(paths.root);
  const plan = moduleOnlyPlan(paths.root, relativeModulePath, scan);
  const strategy = resolveGenerationStrategy(paths, options, process.env, { scan, plan });
  if (!strategy.ok) return strategy;
  progress(options, tr(options, `Generation strategy: runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`, `生成策略：runner=${strategy.runner || "auto"} mode=${displayGenerationMode(strategy.generationMode)} model=${strategy.model || "none"}`));

  const latest = loadLatestRun(paths);
  const run = latest ? { dir: latest.dir, manifest: latest.manifest } : createRun(paths, "generate", options);
  const modulesDir = path.join(run.dir, "modules");
  ensureDir(modulesDir);
  const logsDir = path.join(run.dir, "logs");
  ensureDir(logsDir);

  if (!modulePathExists(paths.root, relativeModulePath)) {
    const warning = `module path not found: ${relativeModulePath}`;
    if (!run.manifest.warnings.includes(warning)) run.manifest.warnings.push(warning);
  }
  const fileName = `${slugify(relativeModulePath) || "project-root"}.md`;
  const moduleFile = path.join(modulesDir, fileName);
  const moduleResult =
    strategy.generationMode === "stub"
      ? {
          ok: true,
          content: moduleStub(relativeModulePath, run.manifest),
          logs: {},
          tokens: run.manifest.tokens,
          warnings: [tr(options, "No local generation tool found; deterministic stub was used.", "未发现可用的本地生成工具，已使用 deterministic stub。")]
        }
      : runModuleGeneration({ paths, run, scan, module: plan.modules[0], strategy, fileName });
  if (!moduleResult.ok) return failRun(run, moduleResult);
  fs.writeFileSync(moduleFile, moduleResult.content, "utf8");

  const artifact = `modules/${fileName}`;
  if (!run.manifest.artifacts.modules.includes(artifact)) run.manifest.artifacts.modules.push(artifact);
  if (!run.manifest.logs.scan) {
    writeJson(path.join(logsDir, "scan.json"), scan);
    writeJson(path.join(run.dir, "plan.json"), plan);
    run.manifest.logs.scan = "logs/scan.json";
    run.manifest.artifacts.plan = "plan.json";
    run.manifest.scanSummary = {
      totalFiles: scan.totalFiles,
      includedFiles: scan.includedFiles.length,
      ignoredFiles: scan.ignoredFiles.count,
      readmeFiles: scan.readmeFiles.map((file) => file.path),
      docsFiles: scan.docsFiles.map((file) => file.path)
    };
    run.manifest.planSummary = {
      modules: plan.modules.length,
      language: plan.language,
      primaryExtension: plan.primaryExtension
    };
  }
  applyModuleGenerationMetadata(run.manifest, strategy, moduleResult);
  run.manifest.updatedAt = new Date().toISOString();
  writeManifest(paths, run);

  return {
    ok: true,
    runId: run.manifest.runId,
    module: relativeModulePath,
    artifact: rel(paths.root, moduleFile),
    message: tr(options, `Generated module candidate document: ${relativeModulePath}`, `已生成模块候选文档：${relativeModulePath}`),
    summary: {
      runner: run.manifest.runner || "auto",
      mode: displayGenerationMode(run.manifest.generationMode),
      model: run.manifest.model || "none",
      run: rel(paths.root, run.dir)
    },
    sections: [{ title: tr(options, "Artifacts", "产物"), items: [rel(paths.root, moduleFile)] }],
    next: ["matspec show"]
  };
}

function runModuleGeneration({ paths, run, scan, module, strategy, fileName }) {
  const promptsDir = path.join(run.dir, "logs/prompts/modules");
  ensureDir(promptsDir);
  const promptFile = path.join(promptsDir, fileName);
  const prompt = buildModulePrompt(scan, module, strategy);
  fs.writeFileSync(promptFile, prompt, "utf8");

  if (strategy.provider === "fake") {
    const result = fakeCompletion({ task: "module", prompt, plan: module, model: strategy.model });
    const tokens = { input: result.usage.input, output: result.usage.output };
    const isReact = strategy.generationMode === "react";
    const logFile = path.join(run.dir, isReact ? "logs/react.json" : "logs/module.json");
    writeJson(logFile, {
      runner: strategy.runner,
      provider: strategy.provider,
      model: strategy.model,
      reason: strategy.generationReason,
      modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), usage: result.usage }],
      tokens
    });
    return {
      ok: true,
      content: result.text,
      tokens,
      logs: {
        ...(isReact ? { react: rel(run.dir, logFile) } : { module: rel(run.dir, logFile) }),
        prompts: { modules: { [module.path]: rel(run.dir, promptFile) } }
      },
      warnings: [isReact ? "P3 fake react module output; no real network LLM was called." : "P2 fake direct module output; no real network LLM was called."]
    };
  }

  const guard = createWorkspaceGuard(paths, run);
  const result = runRunnerTask({ paths, run, strategy, task: `module-${slugify(module.path) || "project-root"}`, prompt });
  if (!result.ok) return result;
  const workspaceError = guard.changed();
  if (workspaceError) return workspaceError;
  const tokens = { input: Math.ceil(prompt.length / 4), output: Math.ceil(result.content.length / 4) };
  const externalLogFile = path.join(run.dir, "logs/external.json");
  writeJson(externalLogFile, {
    runner: strategy.runner,
    model: result.model || strategy.model,
    calls: [result.log],
    prompts: { modules: { [module.path]: rel(run.dir, promptFile) } },
    tokens
  });
  const isReact = strategy.generationMode === "react";
  const moduleLogFile = path.join(run.dir, "logs/module.json");
  writeJson(moduleLogFile, {
    runner: strategy.runner,
    provider: strategy.provider,
    model: result.model || strategy.model,
    reason: strategy.generationReason,
    modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), runnerLog: result.log }],
    tokens
  });
  const reactLogFile = path.join(run.dir, "logs/react.json");
  if (strategy.generationMode === "react") {
    writeJson(reactLogFile, {
      runner: strategy.runner,
      provider: strategy.provider,
      model: result.model || strategy.model,
      reason: strategy.generationReason,
      modules: [{ name: module.name, path: module.path, artifact: `modules/${fileName}`, prompt: rel(run.dir, promptFile), runnerLog: result.log }],
      tokens
    });
  }
  return {
    ok: true,
    content: result.content,
    tokens,
    model: result.model || strategy.model,
    logs: {
      external: rel(run.dir, externalLogFile),
      ...(isReact ? { react: rel(run.dir, reactLogFile) } : { module: rel(run.dir, moduleLogFile) }),
      prompts: { modules: { [module.path]: rel(run.dir, promptFile) } }
    },
    warnings: ["CLI runner module output; artifact was staged under the run directory."]
  };
}

function buildModulePrompt(scan, module, strategy) {
  const moduleFiles = scan.includedFiles.filter((file) => module.path === "." || file === module.path || file.startsWith(`${module.path}/`));
  return `You are the MatSpec module documentation runner (${strategy.runner}).
Read and analyze the repository only.
Do not modify any files.
Do not write to matspec/specs.
Output only the module Markdown. Module docs are white-box intermediate material and may include files, classes, frameworks, and data structures.

${commonOutputRules()}

Module document requirements:
1. Explain module purpose, directory structure, core components, core flows, interfaces/data structures, and key constraints.
2. Base the content on the given module path and read-only repository analysis. Do not invent files.
3. This document is written only to run/modules and does not directly become the final SPEC.

Module: ${module.name}
Path: ${module.path}
Description: ${module.description}

Module files:
${moduleFiles.slice(0, 80).map((file) => `- ${file}`).join("\n") || "- none"}

README context:
${scan.readmeFiles.map((file) => `--- ${file.path}${file.truncated ? " (truncated)" : ""} ---\n${file.content}`).join("\n\n") || "(none)"}

Docs context:
${scan.docsFiles.map((file) => `--- ${file.path}${file.truncated ? " (truncated)" : ""} ---\n${file.content}`).join("\n\n") || "(none)"}
`;
}

export function showLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: tr(options, "No candidate documents found. Run matspec generate first.", "未发现候选文档。请先执行 matspec generate。")
    };
  }
  if (options.json) return latest.manifest;

  const manifest = latest.manifest;
  const modules = manifest.artifacts.modules || [];
  const plan = readRunJson(latest, manifest.artifacts.plan);
  const scan = readRunJson(latest, manifest.logs?.scan);
  const plannedModules = plan?.modules?.length ?? manifest.planSummary?.modules ?? 0;
  const includedFiles = scan?.includedFiles?.length ?? manifest.scanSummary?.includedFiles ?? null;
  const hasFullArtifacts = Boolean(manifest.artifacts.spec && manifest.artifacts.design);
  return {
    ok: true,
    runId: manifest.runId,
    message: tr(options, `Candidate documents: ${manifest.runId}`, `候选文档：${manifest.runId}`),
    items: [
      tr(options, `Status: ${manifest.status}`, `状态：${manifest.status}`),
      `Commit：${manifest.commitId || "unknown"}`,
      "",
      tr(options, "Artifacts:", "产物："),
      manifest.artifacts.spec ? `  ${manifest.artifacts.spec}` : tr(options, "  spec.md not generated", "  spec.md 未生成"),
      manifest.artifacts.design ? `  ${manifest.artifacts.design}` : tr(options, "  design.md not generated", "  design.md 未生成"),
      `  modules/ ${modules.length} files`,
      manifest.artifacts.plan ? `  ${manifest.artifacts.plan}` : tr(options, "  plan.json not generated", "  plan.json 未生成"),
      manifest.logs?.scan ? `  ${manifest.logs.scan}` : tr(options, "  logs/scan.json not generated", "  logs/scan.json 未生成"),
      "",
      tr(options, "Summary:", "摘要："),
      `  generation mode: ${displayGenerationMode(manifest.generationMode)}`,
      `  runner: ${manifest.runner || "auto"}`,
      `  provider: ${manifest.provider || "none"}`,
      `  model: ${manifest.model || "none"}`,
      `  included files: ${includedFiles ?? "unknown"}`,
      `  planned modules: ${plannedModules}`,
      "",
      tr(options, "Location:", "文件位置："),
      `  ${rel(paths.root, latest.dir)}/`,
      ...(hasFullArtifacts ? [] : ["", tr(options, "Hint: this is a module-only run. Run matspec generate before apply.", "提示：这是 module-only run，请先执行 matspec generate 后再 apply。")])
    ],
    next: hasFullArtifacts ? ["matspec apply"] : ["matspec generate"]
  };
}

export function applyLatestRun(options = {}) {
  const paths = projectPaths(options);
  const initializationError = projectInitializationError(paths);
  if (initializationError) return initializationError;
  const latest = loadLatestRun(paths);
  if (!latest) {
    return {
      ok: false,
      code: "NO_GENERATED_RUN",
      message: tr(options, "No candidate documents found. Run matspec generate first.", "未发现候选文档。请先执行 matspec generate。")
    };
  }
  if (latest.manifest.status === "partial_success" && !options.force) {
    return {
      ok: false,
      code: "APPLY_PARTIAL_SUCCESS_REQUIRES_FORCE",
      message: tr(options, "The latest candidate run is partial_success. Use matspec apply --force if you still want to apply it.", "最近一次候选文档为 partial_success。如确认仍要应用，请执行 matspec apply --force。")
    };
  }

  const specSource = path.join(latest.dir, "spec.md");
  const designSource = path.join(latest.dir, "design.md");
  const missing = [specSource, designSource].filter((file) => !fs.existsSync(file));
  if (missing.length) {
    return {
      ok: false,
      code: "RUN_ARTIFACT_MISSING",
      message: tr(options, `Candidate documents are incomplete: ${missing.map((file) => rel(paths.root, file)).join(", ")}`, `候选文档不完整：${missing.map((file) => rel(paths.root, file)).join(", ")}`)
    };
  }

  const quality = validateApplyArtifacts(specSource, designSource, options);
  if (!quality.ok) return quality;

  const specTarget = path.join(paths.specs, "spec.md");
  const designTarget = path.join(paths.specs, "design.md");
  const existing = [specTarget, designTarget].filter((file) => fs.existsSync(file));
  if (existing.length && !options.force) {
    return {
      ok: false,
      code: "APPLY_OVERWRITE_REQUIRED",
      message: tr(options, "matspec/specs/spec.md or matspec/specs/design.md already exists. Use matspec apply --force to overwrite.", "已存在 matspec/specs/spec.md 或 matspec/specs/design.md。如需覆盖，请执行 matspec apply --force。"),
      existing: existing.map((file) => rel(paths.root, file))
    };
  }

  fs.mkdirSync(paths.specs, { recursive: true });
  fs.copyFileSync(specSource, specTarget);
  fs.copyFileSync(designSource, designTarget);

  latest.manifest.applied = true;
  latest.manifest.appliedAt = new Date().toISOString();
  writeManifest(paths, latest);

  return {
    ok: true,
    runId: latest.manifest.runId,
    applied: [rel(paths.root, specTarget), rel(paths.root, designTarget)],
    message: tr(options, `Applied candidate documents: ${latest.manifest.runId}`, `已应用候选文档：${latest.manifest.runId}`),
    items: [rel(paths.root, specTarget), rel(paths.root, designTarget)]
  };
}

function validateApplyArtifacts(specFile, designFile, options = {}) {
  const spec = fs.readFileSync(specFile, "utf8");
  const design = fs.readFileSync(designFile, "utf8");
  const findings = [];
  if (!spec.trim()) findings.push({ level: "error", code: "SPEC_EMPTY", path: "spec.md", message: tr(options, "spec.md is empty.", "spec.md 为空。") });
  if (!design.trim()) findings.push({ level: "error", code: "DESIGN_EMPTY", path: "design.md", message: tr(options, "design.md is empty.", "design.md 为空。") });

  for (const section of requiredSpecSections()) {
    if (!containsSection(spec, section)) {
      findings.push({ level: "error", code: "SPEC_SECTION_MISSING", path: "spec.md", message: tr(options, `spec.md is missing required section: ${section}`, `spec.md 缺少固定章节：${section}`) });
    }
  }
  for (const section of requiredDesignSections()) {
    if (!containsSection(design, section)) {
      findings.push({ level: "error", code: "DESIGN_SECTION_MISSING", path: "design.md", message: tr(options, `design.md is missing required section: ${section}`, `design.md 缺少固定章节：${section}`) });
    }
  }
  for (const finding of forbiddenGeneratedOutput(spec, "spec.md", options)) findings.push(finding);
  for (const finding of forbiddenGeneratedOutput(design, "design.md", options)) findings.push(finding);

  if (!findings.length) return { ok: true };
  return {
    ok: false,
    code: "APPLY_QUALITY_FAILED",
    message: tr(options, "Candidate documents failed pre-apply quality checks.", "候选文档未通过 apply 前质量检查。"),
    findings,
    next: isZh(options) ? ["matspec show", "查看 .matspec-cli/runs/{run-id}/spec.md 和 design.md"] : ["matspec show", "Inspect .matspec-cli/runs/{run-id}/spec.md and design.md"]
  };
}

function containsSection(text, section) {
  return text.replace(/\s+/g, "").toLowerCase().includes(section.replace(/\s+/g, "").toLowerCase());
}

function forbiddenGeneratedOutput(text, file, options = {}) {
  const findings = [];
  const trimmed = text.trim();
  if (/^```(?:md|markdown)?\s*#/i.test(trimmed) && /```\s*$/i.test(trimmed)) {
    findings.push({ level: "error", code: "WHOLE_DOCUMENT_CODE_FENCE", path: file, message: tr(options, `${file} is wrapped entirely in a Markdown code fence.`, `${file} 被整体包裹在 Markdown 代码围栏中。`) });
  }
  const forbidden = [
    { pattern: /\b(?:this|the)\s+sandbox\b|\bsandbox\s+environment\b|\bread-?only\s+sandbox\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "sandbox environment" },
    { pattern: /\bread-?only\s+filesystem\b|\bfilesystem\s+access\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "filesystem access" },
    { pattern: /\bread-?only\s+(?:mode|environment|access)\b/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "read-only environment" },
    { pattern: /cannot write files|could not write files|can't write files/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "cannot write files" },
    { pattern: /copy (?:this|the following|into|to your repo)/i, code: "RUNNER_ENVIRONMENT_TEXT", label: "copy into repo" }
  ];
  for (const item of forbidden) {
    if (item.pattern.test(text)) {
      findings.push({ level: "error", code: item.code, path: file, message: tr(options, `${file} contains runner environment text: ${item.label}`, `${file} 包含 runner 环境说明：${item.label}`) });
    }
  }
  return findings;
}

function progress(options, message) {
  if (typeof options.progress === "function") options.progress(message);
}

function displayGenerationMode(mode) {
  if (mode === "react") return "module-first";
  if (mode === "direct") return "whole-project-direct";
  return mode || "unknown";
}

function createRun(paths, type, options = {}) {
  const runId = uniqueRunId(paths);
  const dir = path.join(paths.runtime, "runs", runId);
  fs.mkdirSync(dir, { recursive: true });
  const manifest = {
    runId,
    type,
    status: "generated",
    createdAt: new Date().toISOString(),
    root: paths.root,
    commitId: currentCommit(paths.root),
    runner: options.runner || "auto",
    generationMode: "stub",
    provider: null,
    model: options.model || null,
    probeModels: {
      requested: Boolean(options.probe_models),
      status: options.probe_models ? "not_implemented" : "not_requested"
    },
    artifacts: {
      spec: null,
      design: null,
      plan: null,
      modules: []
    },
    logs: {
      scan: null,
      llm: null,
      prompts: {}
    },
    warnings: ["P0 deterministic stub output; no LLM was called."],
    tokens: {
      input: 0,
      output: 0
    },
    applied: false
  };
  return { dir, manifest };
}

function applyGenerationMetadata(manifest, metadata) {
  manifest.runner = metadata.runner || manifest.runner;
  manifest.generationMode = metadata.generationMode;
  manifest.provider = metadata.provider || null;
  manifest.model = metadata.model || null;
  manifest.tokens = metadata.tokens || manifest.tokens;
  manifest.generationReason = metadata.reason || null;
  manifest.warnings = metadata.warnings || manifest.warnings;
  if (metadata.logs?.llm) manifest.logs.llm = metadata.logs.llm;
  if (metadata.logs?.react) manifest.logs.react = metadata.logs.react;
  if (metadata.logs?.external) manifest.logs.external = metadata.logs.external;
  if (metadata.logs?.prompts) manifest.logs.prompts = metadata.logs.prompts;
  if (metadata.modules) manifest.artifacts.modules = metadata.modules;
}

function applyModuleGenerationMetadata(manifest, strategy, result) {
  manifest.runner = strategy.runner || manifest.runner;
  manifest.generationMode = strategy.generationMode;
  manifest.provider = strategy.provider || null;
  manifest.model = result.model || strategy.model || null;
  manifest.tokens = result.tokens || manifest.tokens;
  manifest.generationReason = strategy.generationReason || null;
  if (result.warnings) {
    manifest.warnings = [...new Set([...manifest.warnings, ...result.warnings])];
  }
  if (result.logs?.external) manifest.logs.external = result.logs.external;
  if (result.logs?.react) manifest.logs.react = result.logs.react;
  if (result.logs?.module) manifest.logs.module = result.logs.module;
  if (result.logs?.prompts) {
    manifest.logs.prompts = {
      ...(manifest.logs.prompts || {}),
      ...(result.logs.prompts || {})
    };
  }
}

function failRun(run, error) {
  run.manifest.status = "failed";
  run.manifest.error = {
    code: error.code,
    message: error.message
  };
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  return error;
}

function writeManifest(paths, run) {
  writeJson(path.join(run.dir, "manifest.json"), run.manifest);
  writeJson(path.join(paths.runtime, "runs", "latest.json"), {
    runId: run.manifest.runId,
    manifest: rel(paths.root, path.join(run.dir, "manifest.json"))
  });
}

function loadLatestRun(paths) {
  const latestFile = path.join(paths.runtime, "runs", "latest.json");
  const latest = readJson(latestFile);
  if (latest?.runId) {
    const dir = path.join(paths.runtime, "runs", latest.runId);
    const manifest = readJson(path.join(dir, "manifest.json"));
    if (manifest) return { dir, manifest };
  }

  const runsDir = path.join(paths.runtime, "runs");
  if (!fs.existsSync(runsDir)) return null;
  const manifests = fs
    .readdirSync(runsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dir = path.join(runsDir, entry.name);
      return { dir, manifest: readJson(path.join(dir, "manifest.json")) };
    })
    .filter((run) => run.manifest?.createdAt && run.manifest.status !== "failed")
    .sort((a, b) => String(b.manifest.createdAt).localeCompare(String(a.manifest.createdAt)));
  return manifests[0] || null;
}

function projectInitializationError(paths) {
  if (!fs.existsSync(paths.runtime) || !fs.existsSync(paths.matspec)) {
    return {
      ok: false,
      code: "MATSPEC_NOT_INITIALIZED",
      message: "Missing MatSpec project structure. Run matspec init first.",
      next: ["matspec init"]
    };
  }
  return null;
}

function validateModuleRunner(options) {
  const runner = options.runner || "auto";
  if (runner === "auto") return null;
  return {
    ok: false,
    code: "RUNNER_NOT_IMPLEMENTED",
    runner,
    message: `Runner is not implemented for module generation: ${runner}. Use the default runner or --runner auto.`,
    next: ["matspec generate"]
  };
}

function uniqueRunId(paths) {
  const base = timestampId();
  let runId = base;
  let suffix = 1;
  while (fs.existsSync(path.join(paths.runtime, "runs", runId))) {
    suffix += 1;
    runId = `${base}-${suffix}`;
  }
  return runId;
}

function timestampId(date = new Date()) {
  const pad = (value, size = 2) => String(value).padStart(size, "0");
  return [
    date.getFullYear(),
    pad(date.getMonth() + 1),
    pad(date.getDate()),
    pad(date.getHours()),
    pad(date.getMinutes()),
    pad(date.getSeconds()),
    pad(date.getMilliseconds(), 3)
  ].join("");
}

function currentCommit(root) {
  const result = spawnSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: root,
    encoding: "utf8",
    windowsHide: true,
    timeout: 2000
  });
  return result.status === 0 ? result.stdout.trim() : null;
}

function normalizeModulePath(root, modulePath) {
  const resolved = path.isAbsolute(modulePath) ? modulePath : path.join(root, modulePath);
  const relative = normalizePath(path.relative(root, resolved));
  return relative && !relative.startsWith("..") ? relative : normalizePath(modulePath);
}

function modulePathExists(root, modulePath) {
  if (modulePath === ".") return true;
  return fs.existsSync(path.join(root, modulePath));
}

function readRunJson(run, relativePath) {
  if (!relativePath) return null;
  return readJson(path.join(run.dir, relativePath), null);
}

function moduleOnlyPlan(root, modulePath, scan) {
  const primaryExtension = scan.primaryExtension || null;
  return {
    projectName: path.basename(root),
    language: null,
    primaryExtension,
    modules: [
      {
        name: moduleName(modulePath),
        path: modulePath,
        description: modulePath === "." ? "Project root module requested by user." : `Module requested by user at ${modulePath}.`
      }
    ]
  };
}

function moduleName(modulePath) {
  if (modulePath === ".") return "Project Root";
  const base = modulePath.split("/").filter(Boolean).pop() || "Module";
  return base
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function designStub(root, manifest) {
  return `${STUB_MARKER}
# MatSpec Implementation Design

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. Design Overview

This deterministic stub validates the MatSpec candidate document generation pipeline.

## 2. System Architecture

The stub does not call an LLM or external agent. The CLI creates the run directory, writes artifacts, and maintains the manifest.

## 3. Data Model

manifest.json records the run ID, status, artifacts, runner, model metadata, and apply state.

## 4. Interface Design

User-facing entry points are matspec generate, matspec show, matspec apply, and matspec generate module <path>.

## 5. Core Flow Design

generate writes candidate documents, show displays the latest run, and apply publishes reviewed artifacts to matspec/specs with overwrite protection.

## 6. Algorithm Design

Stub mode does not use complex algorithms.

## 7. Caching Design

Stub mode does not use caching.

## 8. Error Handling Design

Existing authoritative documents are not overwritten unless --force is provided.

## 9. Observability

The run directory stores the manifest and generation logs.

## 10. Security Design

Stub content is only a fallback artifact and does not represent a real project design conclusion.
`;
}

function specStub(root, manifest) {
  return `${STUB_MARKER}
# MatSpec SPEC

Run: ${manifest.runId}
Repository: ${path.basename(root)}

## 1. Component Purpose

This component uses the MatSpec CLI to manage candidate documents and publish reviewed authoritative documents.

## 2. Domain Terminology

- Candidate document: a generated document stored in a run directory before apply.
- Authoritative document: spec.md or design.md under matspec/specs.
- Run: an isolated result directory created by one generation action.

## 3. Actors and Boundaries

The CLI owns artifact writing, review display, and apply. External agents do not write authoritative documents directly.

## 4. DFX Constraints

Applying candidate documents must respect overwrite protection; existing authoritative documents are preserved by default.

## 5. Core Capabilities

- Users can generate candidate spec.md and design.md.
- Users can review the latest candidate document summary.
- Users can explicitly apply the latest candidate documents.
- Users can generate review material for a single module.

## 6. Data Constraints

- generate writes only to .matspec-cli/runs.
- show can return the latest run manifest.
- apply fails without --force when the target already exists.
`;
}

function moduleStub(modulePath, manifest) {
  return `${STUB_MARKER}
# Module Design: ${modulePath}

Run: ${manifest.runId}

## 1. Module Purpose

This is a deterministic stub module document for ${modulePath}.

## 2. Directory Structure

The stub does not analyze the full file tree; real generation should add repository scan and module planning details.

## 3. Core Components

To be filled by real code analysis.

## 4. Core Flows

This file is stored only under run/modules and is not applied to matspec/specs.

## 5. Interfaces and Data Structures

To be confirmed.

## 6. Key Constraints

The deterministic stub does not call an LLM or external runner.
`;
}
